### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by vitaly-t** [qrawl/sql-uglifier#1]
I was going to test it for some advanced features, but it fails on the most basic stuff:

``` sql
select * from test
```

outputs:

``` sql
 elect * from test
```

**Comment by pierreprinetti** [comment]
Hi there. Thank you for reporting.
It seems to behave strangely with CRLF files (Windows end-of-line character). I'll look into it.

**Comment by pierreprinetti** [comment]
Just pushed version 1.0.4 with support for Windows files.

```
npm update -g sql-uglifier
```

Please check if it is working properly now.

**Comment by vitaly-t** [comment]
The bug I described was fixed, but the next issue I saw - it doesn't remove single-line `--comments`.

Anyway, since I needed a reliable minification specifically for PostgreSQL scripts, I wrote one of my own yesterday - [pg-minify](https://github.com/vitaly-t/pg-minify).

Thank you for your support!
